# Dependencies
markdown:           redcarpet
highlighter:        pygments

# Permalinks
permalink:          pretty

# Setup
title:              Wisembly
tagline:            'Ideas are everywhere'
description:        'Random Wisembly developpers thoughts and more or less useful findings..'

authors:
  guillaumepotier:
    name:           Guillaume Potier
    display_name:   guillaumepotier
    gravatar:       d9297b88ef842ae8ccc562ad3b4cc1e1
    email:          guillaume@wisembly.com
    web:            http://imctobitch.com
    twitter:        guillaumepotier
    github:         guillaumepotier

  gabrielcousin:
    name:           Gabriel Cousin
    display_name:   gabrielcousin
    gravatar:       f8847fb0b810b70d5fbc8f7b97c266b8
    email:          gabriel@wisembly.com
    twitter:        gabrielcousin
    github:         gabrielcousin

paginate:           5
related_limit:      3

# Custom vars
version:            0.0.1

urls:
  github:           https://github.com/wisembly
  corpo:            http://wisembly.com
