# Dependencies
markdown:           redcarpet
redcarpet:
  extensions:       ["strikethrough"]

gems: [jekyll-paginate]

# Permalinks
permalink:          pretty

# Setup
title:              Wisembly dev blog
tagline:            'Ideas are everywhere'
description:        'Random Wisembly developpers thoughts and more or less useful findings…'

authors:
  guillaumepotier:
    name:           Guillaume Potier
    display_name:   guillaumepotier
    gravatar:       d9297b88ef842ae8ccc562ad3b4cc1e1
    email:          guillaume@wisembly.com
    twitter:        guillaumepotier
    github:         guillaumepotier

  gabrielcousin:
    name:           Gabriel Cousin
    display_name:   gabrielcousin
    gravatar:       f8847fb0b810b70d5fbc8f7b97c266b8
    email:          gabriel@wisembly.com
    twitter:        gabrielcousin
    github:         gabrielcousin

paginate:           5
related_limit:      3

# Custom vars
version:            0.0.1

menu_products:
  - name: Wisembly
    link: http://wisembly.com
  - name: Solid
    link: http://getsolid.io

menu_opensource:
  - name: ParsleyJS
    link: http://parsleyjs.org
  - name: Tapestry
    link: http://tapestry.wisembly.com
  - name: CalendArt
    link: https://github.com/Wisembly/CalendArt
  - name: Elephant.io
    link: http://elephant.io/
